{% set name = "ParmEd" %}
{% set version = "4.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 56e7c0a018d086ff6253265be6755e7965e7ac3bef358073787ca89df08e2015

build:
  number: 2
  entry_points:
    - parmed = parmed.scripts:clapp
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '
  skip: true  # [win and vc<14]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pip
    - setuptools
    - python
  run:
    - numpy >=1.14,<2.3
    - pandas
    - python

test:
  imports:
    - parmed
    - parmed.amber
    - parmed.amber.mdin
    - parmed.charmm
    - parmed.formats
    - parmed.formats.pdbx
    - parmed.gromacs
    - parmed.modeller
    - parmed.namd
    - parmed.openmm
    - parmed.rdkit
    - parmed.rosetta
    - parmed.tinker
    - parmed.tools
    - parmed.tools.simulations
    - parmed.unit
    - parmed.utils
    - parmed.utils.fortranformat
  commands:
    - parmed --help

about:
  home: https://parmed.github.io/ParmEd/html/index.html
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: Amber parameter file editor
  doc_url: https://parmed.github.io/ParmEd/html/index.html
  description: |
    ParmEd is a package designed to facilitate creating and easily 
    manipulating molecular systems that are fully described by a 
    common classical force field. Supported force fields include 
    Amber, CHARMM, AMOEBA, and several others that share a similar 
    functional form (e.g., GROMOS).

extra:
  recipe-maintainers:
    - chrisbarnettster
    - simonbray
    - tsenapathi
    - jaimergp
    - swails
